- hosts: all
  tasks:
  - ansible.windows.win_domain_membership:
      dns_domain_name: "{{ domain }}"
      hostname: "{{ inventory_hostname }}"
      domain_admin_user: "{{ domain_admin_user }}"
      domain_admin_password: "{{ domain_admin_password }}"
      domain_ou_path: "{{ domain_ou_path }}"
      state: domain
    register: domain_state

  - ansible.windows.win_reboot:
    when: domain_state.reboot_required
